### ISSUE TITLE
Allow nested folders and project specific settings

### ISSUE THREAD

**Issue by borestad** [matthiasg/sublime-mocha-runner#1]
Hi.
First, thanks for a great idea!

I just noticed that the project doesn't really work that well with nested folders, like
test/unit/foo.test.coffee

It also makes assumtions that every folder inside test is testable, i.e
test/vendor/notest.js

I propose creating a project specific file in the root of your project, called something like ".sublime-mocha-runner", and in that one create options for i.e only allowing specific files (*.spec or *.test)

**Comment by matthiasg** [comment]
Have you looked into mocha.opts? We put a mocha.opts file into the test folder and use that to override settings...

Cheers,
Matthias Götzke

Gesendet von meinem Windows Phone

---

From: Johan Borestad
Sent: 03.01.2013 22:31
To: matthiasg/sublime-mocha-runner
Subject: [sublime-mocha-runner] Allow nested folders and project specific settings (#1)

Hi.
First, thanks for a great idea!

I just noticed that the project doesn't really work that well with nested folders, like
test/unit/foo.test.coffee

It also makes assumtions that every folder inside test is testable, i.e
test/vendor/notest.js

I propose creating a project specific file in the root of your project, called something like ".sublime-mocha-runner", and in that one create options for i.e only allowing specific files (*.spec or *.test)

**Comment by matthiasg** [comment]
is this still something you need or want ? I will look into making it more sublime3 compatible soon and while I am at it :)

**Comment by matthiasg** [comment]
Too old (switched editor)
